Porfolio
valt19/porfolio- pull request #28
Opened 2023-04-28 11:06 UTC by valt19

# portfolio 
In this project:
add linters
add html
styled the cards
updated the README file

2023-04-28 11:56 UTC, Strangeal requested changes
Hi @valt19, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media0.giphy.com/media/BM10SaUSoT789SJkvf/giphy.gif)

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
**Congratulations 🎉 on the impressive work you've done so far. I've made some suggestions below to help you improve your project so kindly take a look at it and if you don't understand anything please don't hesitate to ask. Best of luck! 🤞🏻. Using `inline` comments would have been the best but since I don't have access to your `index.html` in this pull request. I will do my best to explain the changes here. Let's get started.**

- [ ] Consider removing the `welcome` text you have on the `nav` as it's not on the `Figma` template design. This will make your design look accurate and look exactly like that of the `Figma` design template. See below for more details:
<table>
<tr>
<th align="middle">Figma design</th>
<th align="middle">Your design</th>
</tr>
<tr>
<td>
<img width="381" alt="Screenshot 2023-04-28 at 04 44 59" src="https://user-images.githubusercontent.com/107192076/235137510-fd7621c1-ef95-452f-8191-5ef8ac211fe0.png">
</td>
<td>
<img width="371" alt="Screenshot 2023-04-28 at 11 30 11" src="https://user-images.githubusercontent.com/107192076/235137714-a08f7d79-c09f-4088-a860-17389d99c3fa.png">
</td>
</tr>
</table>

- [ ] Consider moving the Iine break `br` in your `h1` between **Hey there** and  **I’m Mariane**. This way the text  **I’m Mariane** will be wrapped onto the next line and that will make your design look exactly like that of the `Figma` design.
https://github.com/valt19/porfolio-/blob/f31491cd0801972b57359ad3c1b5bac7db566183/index.html#L21

- [ ] Kindly consider the use of heading (`h2`, `h3`, `h4`) tags instead of the `span` tag to display the sub-heading of the main heading. Using heading tags conveys the semantic meaning of a subheading and helps improve the accessibility and structure of the document. Therefore, using heading tags instead of the `span` tag would be more semantically correct in this context.
https://github.com/valt19/porfolio-/blob/f31491cd0801972b57359ad3c1b5bac7db566183/index.html#L22

- [ ] Consider including `alt` text for your images. Including `alt` text in their images is not only good for accessibility, but it's also an essential part of good web development practice. The `alt` attribute is used to describe the contents of an image to users who may not be able to see the image. This includes users with visual impairments, users who use screen readers, and users who may have slow internet connections or have turned off image loading to save bandwidth.

https://github.com/valt19/porfolio-/blob/f31491cd0801972b57359ad3c1b5bac7db566183/index.html#L27-L46

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 08:35 UTC, jerryowusu requested changes
Hi @valt19  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![soclose2](https://user-images.githubusercontent.com/65233860/235293395-e2c23b90-56e5-4545-a4f7-c2558cc0cc84.gif)


 ## Highlights
Nice design so far :+1: 
Great effort in making the requested changes :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 08:35 UTC, jerryowusu commented on index.html
> +      <!-- <a href="welcome" class="head">Welcome</a> -->
Nice work so far. However, as part of HTML/CSS best practices, do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.
Kindly consider removing the commented line of code from your codebase. :pray:

2023-04-29 08:35 UTC, jerryowusu commented on index.html
> +      <span class="hey-text2"> I’m a software developer</span></h2>
[OPTIONAL] Kindly make sure that this part looks exactly like the design in all screen sizes of the mobile version. There should be a line break between the `I'm a software` and `developer`, however, at screenwidths greater than 600px, they stay on the same line. Kindly update your app accordingly. :pray: 

### Your app below 600px 

![Screenshot from 2023-04-29 08-28-48](https://user-images.githubusercontent.com/65233860/235293300-afbc7380-3784-496c-94f1-db0c47c1c855.png)


### Your app above 600px

![Screenshot from 2023-04-29 08-27-20](https://user-images.githubusercontent.com/65233860/235293291-d2b80d90-79ba-49cf-90c3-db3df4f27b48.png)



### Actual design 


![Screenshot from 2023-04-29 08-25-55](https://user-images.githubusercontent.com/65233860/235293284-98106460-1240-4522-a2df-b68e972d72e5.png)

2023-04-29 09:29 UTC, usorfaitheloho approved these changes
Hi @valt19  👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 09:32 UTC, merged