Contact branch
valt19/porfolio- pull request #6
Opened 2023-02-21 07:55 UTC by valt19

Portfolio project by valt19.
Bug fix
Run local stylelint config command(npx stylelint "**/*.{css,scss}" --fix.
Checklist
-[ ] My code follows the style guidelines of this project

I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings

2023-02-21 08:09 UTC, wayungi reviewed
Hi @valt19  
![image](https://user-images.githubusercontent.com/99656687/220284938-37e6889a-58a0-4919-8f26-3ddb15647aec.png)


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

- [ ] This is a pair programming activity but you have done it all alone. Please pair pragramm with your partner.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-21 10:46 UTC, mahbubul14 requested changes
Hi < Student Mention > ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly update the getting started section. This should be an example of how you may give instructions on setting up your project locally. Also, there is no link in the author section. The text should be linkable.

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-21 10:46 UTC, mahbubul14 commented on index.html
> +
- [ ] Button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template. Kindly work on it. :+1: 

![2023-02-21_01-55](https://user-images.githubusercontent.com/70483835/220323219-5b15a1df-cac5-4ebd-8c05-2fb3fce8ac58.png)

2023-02-21 16:28 UTC, Owusu-Desmond requested changes
Hi @valt19 :wave: 

You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 16:28 UTC, Owusu-Desmond commented on style.css
> +}
- [ ] Please as requested by the previous code reviewer, interactions such as hover, active (when it's pressed), disabled and enable (default state) should be styled based on the design you selected as shown in the Figma template. Kindly work on it
  
  ### Your design
  ![Screenshot from 2023-02-21 16-10-19](https://user-images.githubusercontent.com/92303891/220402038-75d6dc30-cbd7-42f9-bb48-4a09c7bdc8d8.png)
  
  ### Figma design
  ![image](https://user-images.githubusercontent.com/92303891/220402942-bc1144cc-5c1b-420b-83cd-ed6ca9c5fbdd.png)

2023-02-21 17:50 UTC, jasonfelice approved these changes
Hi @valt19, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

## Highlights
No Linter errors✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 13:22 UTC, merged

2023-05-03 15:44 UTC, emmiiorji reviewed
Hi @valt19, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220870678-4f45b7ed-1d79-4e6a-9338-da59224b2cbc.gif'/>
</div>

You have submitted a pair programming project without commits from your new partner(s). I can see that this might be a repeated milestone. While straightway project approval is guaranteed for repeated solo projects, this is a pair programming milestone and you're required to collaborate with your new team on the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-06 05:47 UTC, emmiiorji commented
Hi @valt19, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/236602878-e14b43a3-a2e2-4b65-b93f-46dde73a8a1d.gif'/>
</div>

As I mentioned earlier, you have submitted a pair programming project without commits from your new partner(s). I can see that this might be a repeated milestone. While straightway project approval is guaranteed for repeated solo projects, this is a pair programming milestone and you're required to collaborate with your new team on the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._