Desktop branch
valt19/porfolio- pull request #7
Opened 2023-02-25 15:01 UTC by valt19

I made some changes in css and html
I updated the desktop-version-branch and made it responsive

2023-02-25 16:06 UTC, mukhammadrizooff requested changes
Hi @valt19, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 16:06 UTC, mukhammadrizooff commented on index.html
>  <h1 class="hey-text">Hey there. I’m Mariane <br>
- [ ] [REQUIRED] Good job so far! Please give correct style to `Home Page` and also `Navigation` elements like [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=FM3eIBvsAszGSaO5-0)🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/221366847-883dddd8-10a1-4da9-ab05-997514b12824.png)

2023-02-25 16:06 UTC, mukhammadrizooff commented on index.html
> +      <div class="project-cards">
- [ ] [REQUIRED] Good job so far! Please style the layout of the work cards like [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=FM3eIBvsAszGSaO5-0) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/221367043-fd6f47a0-858c-4212-b43a-94b152f64b7a.png)

2023-02-25 16:06 UTC, mukhammadrizooff commented on index.html
> +      <ul class="icons">
- [ ] [REQUIRED] Good job so far! Please give the right style to the `text` on the left and I think you have not created the long `Horizontal` line in the footer, please follow my suggestions above 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/221367194-864552a0-d8bf-43f2-b2ca-97ffcc37fa1b.png)

2023-02-25 18:36 UTC, AlphaNtihinduka requested changes
## Hi @rosemutai 🙋‍♂️

Good job working on your desktop version of the portifolio. You have done the design to the best expectation and incredibly well. 👏  
 
You still need to implement few on the project but you are almost there!!! 🚶 : 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-02-25 18:36 UTC, AlphaNtihinduka commented on style.css
>  }
- [ ] As the previous reviewer suggested, kindly try as much as possible to stick to the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=iqWpkNWp3niX7g3e-0). Therefore I suggest that you ensure the color of the nav links match that of Figma design 😎 

Your design 😎 
![image](https://user-images.githubusercontent.com/99394374/221373501-c703d724-51e5-4055-a242-663cbf3cfbfa.png)

2023-02-25 18:36 UTC, AlphaNtihinduka commented on style.css
> +
- [ ] You have done well to ensure that you have the desktop version of the application 👏 . However, as the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements) suggest, kindly consider using media queries in your CSS file to make your desktop version look like the template you selected (Desktop: >=768px) ☺️ 
- [ ] Additionally, I have noticed the horizontal scroll in your desktop application. The traditional horizontal scrollbar burdens the user by requiring constant attention and greater physical effort to maintain the dragging 😞 .

2023-02-25 19:53 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @valt19, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 13:22 UTC, merged

2023-05-03 16:56 UTC, ABDULALI3468 reviewed
Hi @valt19 , 👍 

# APPROVED 💯 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
☑️ Approving PR already approved before.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._